---
- name: Install the required packages
  ansible.builtin.apt:
    pkg:
    - ca-certificates
    - curl
    - gnupg
    - lsb-release
    update_cache: yes

- name: Add a gpg key for Docker repo
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    keyring: /etc/apt/keyrings/docker.gpg
    state: present

- name: Get the Ubuntu codename version
  shell: 'echo \
  deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
  "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable'
  register: ubuntu_codename

- name: Output of ubuntu_codename
  debug:
    msg: "{{ ubuntu_codename.stdout_lines }}" 

- name: Add Google Cloud Repository
  apt_repository:
    repo: "{{ ubuntu_codename.stdout_lines[0] }}"
    state: present

- name: Install the Docker components
  ansible.builtin.apt:
    pkg:
    - docker-ce 
    - docker-ce-cli 
    - containerd.io 
    - docker-buildx-plugin 
    - docker-compose-plugin